import type { ForgePlaybook } from '@/types'

export const PLAYBOOKS: ForgePlaybook[] = [
  {
    id: 'one-day-landing',
    title: 'Landing de confianza en 1 dia',
    category: 'Conversion',
    oneLiner: 'Idea vaga -> oferta clara -> landing -> CTA -> medicion.',
    bestFor: ['servicios', 'infoproductos', 'SaaS', 'ecommerce'],
    outcome: 'Salir con una landing lista para validar y cobrar.',
    sprintSteps: [
      'Definir cliente ideal, dolor y promesa.',
      'Construir oferta simple con 1 CTA y 1 objecion resuelta.',
      'Diseñar landing, FAQ y prueba social inicial.',
      'Publicar y medir clics, mensajes o ventas.',
    ],
    monetization: ['venta directa', 'lead magnet', 'reserva de llamada', 'waitlist'],
    deliverables: ['headline', 'estructura landing', 'CTA', 'FAQ', 'metrica inicial'],
    tools: ['Forge', 'Vault', 'Gemini free o modo manual'],
  },
  {
    id: 'financial-analyst-free',
    title: 'Analista financiero free',
    category: 'Finanzas',
    oneLiner: 'Tomar ingresos, costos y flujo de caja para decidir rapido.',
    bestFor: ['freelancers', 'agencias', 'negocios pequenos'],
    outcome: 'Un tablero simple para saber que vender, cortar o escalar.',
    sprintSteps: [
      'Cargar ingresos, costos fijos y costos variables.',
      'Separar unidades rentables de las que drenan caja.',
      'Definir meta semanal de caja y margen.',
      'Crear checklist de decisiones financieras de 15 minutos.',
    ],
    monetization: ['control de caja', 'pricing', 'upsells', 'recorte de fugas'],
    deliverables: ['resumen financiero', 'acciones de caja', 'reglas de gasto', 'metricas'],
    tools: ['Sheets', 'Forge', 'modo manual'],
    inspiredBy: 'Financial Analyst quickstart',
  },
  {
    id: 'python-windows-automation',
    title: 'Automatizacion Python para Windows',
    category: 'Automatizacion',
    oneLiner: 'Scripts para eliminar tareas repetitivas de escritorio.',
    bestFor: ['backoffice', 'reportes', 'archivos', 'operaciones'],
    outcome: 'Un script que ahorra tiempo desde el primer dia.',
    sprintSteps: [
      'Elegir tarea repetitiva y medir tiempo perdido.',
      'Mapear inputs, archivos, carpetas y salidas.',
      'Generar script con validaciones y logs simples.',
      'Probar, documentar y dejar doble click o comando listo.',
    ],
    monetization: ['ahorro de tiempo', 'servicio de automatizacion', 'producto interno'],
    deliverables: ['script', 'checklist de prueba', 'manejo de errores', 'paso a paso'],
    tools: ['Forge', 'Vault', 'Python'],
  },
  {
    id: 'content-engine',
    title: 'Motor de contenido rentable',
    category: 'Contenido',
    oneLiner: 'Un problema, una promesa y 30 piezas derivadas.',
    bestFor: ['marca personal', 'agencia', 'educacion', 'SaaS'],
    outcome: 'Calendario con piezas que venden y no solo publican.',
    sprintSteps: [
      'Definir una gran promesa y 3 objeciones frecuentes.',
      'Crear pilares de contenido y CTAs por etapa.',
      'Producir formatos largos y derivar shorts, posts y emails.',
      'Medir piezas que traen leads o reuniones.',
    ],
    monetization: ['consultoria', 'captacion', 'venta por contenido'],
    deliverables: ['calendario', 'hooks', 'CTAs', 'sistema de reciclaje'],
    tools: ['Forge', 'Library', 'modo manual'],
  },
  {
    id: 'client-acquisition',
    title: 'Adquisicion de clientes en frio',
    category: 'Ventas',
    oneLiner: 'Oferta concreta + lista concreta + outreach simple + follow-up.',
    bestFor: ['servicios', 'B2B', 'freelance', 'agencias'],
    outcome: 'Pipeline inicial de reuniones o demos.',
    sprintSteps: [
      'Definir nicho y promesa cuantificable.',
      'Listar 50 prospectos con criterio real.',
      'Escribir opener corto, diagnostico y CTA.',
      'Ejecutar seguimiento sistematico durante 7 dias.',
    ],
    monetization: ['retainers', 'setup fee', 'consultoria'],
    deliverables: ['script de outreach', 'seguimientos', 'objeciones', 'KPI diario'],
    tools: ['Forge', 'Vault', 'email o WhatsApp'],
  },
  {
    id: 'support-agent',
    title: 'Agente de soporte y FAQ',
    category: 'Agentes',
    oneLiner: 'Base de conocimiento minima + prompts + handoff claro.',
    bestFor: ['productos', 'membresias', 'servicios digitales'],
    outcome: 'Atencion mas rapida y menos tickets repetidos.',
    sprintSteps: [
      'Reunir preguntas frecuentes y respuestas aprobadas.',
      'Definir cuando responde y cuando escala a humano.',
      'Crear prompt, checklist y politica de seguridad.',
      'Probar con conversaciones reales.',
    ],
    monetization: ['ahorro operativo', 'mejor conversion por soporte'],
    deliverables: ['base FAQ', 'prompt del agente', 'handoffs', 'métricas'],
    tools: ['Forge', 'Vault', 'playbooks'],
    inspiredBy: 'Customer Support Agent quickstart',
  },
  {
    id: 'browser-research',
    title: 'Investigacion de mercado y competencia',
    category: 'Research',
    oneLiner: 'Recolectar señales del mercado y convertirlas en decisiones.',
    bestFor: ['nuevos negocios', 'reposicionamiento', 'ofertas'],
    outcome: 'Mapa rapido de oportunidades, pricing y huecos.',
    sprintSteps: [
      'Definir 5 competidores y 3 sustitutos.',
      'Extraer promesas, pricing y objeciones repetidas.',
      'Sintetizar huecos del mercado y una oferta diferenciada.',
      'Construir decision de posicionamiento en una pagina.',
    ],
    monetization: ['mejor oferta', 'mejor pricing', 'mejor ICP'],
    deliverables: ['tabla de competidores', 'huecos', 'nueva oferta', 'CTA'],
    tools: ['navegador', 'Vault', 'Forge'],
    inspiredBy: 'Browser Tools quickstart',
  },
  {
    id: 'autonomous-coding',
    title: 'Agente de codigo y entrega',
    category: 'Codigo',
    oneLiner: 'Tomar un repo, detectar bloqueos y ejecutar cambios verificables.',
    bestFor: ['apps web', 'automatizaciones', 'MVPs'],
    outcome: 'Version funcional con pruebas y deploy listos.',
    sprintSteps: [
      'Definir objetivo tecnico y criterio de aceptacion.',
      'Inspeccionar repo y detectar piezas faltantes.',
      'Implementar cambios con pruebas y validacion.',
      'Dejar checklist de deploy y monitoreo.',
    ],
    monetization: ['MVPs rapidos', 'servicios productizados', 'templates'],
    deliverables: ['cambios de codigo', 'pruebas', 'deploy notes', 'riesgos'],
    tools: ['Forge', 'Vault', 'repo local'],
    inspiredBy: 'Autonomous Coding Agent quickstart',
  },
]
